export const bannedWords = {
  explicit: [
    "xxx",
    "porn",
    "nsfw",
    "nude",
    "sex",
    "erotic",
    "fetish",
    "hardcore",
    "explicit",
    "adult",
    "camgirl",
    "onlyfans",
    "lingerie",
    "strip",
    "escort",
    "lapdance",
    "peep",
    "voyeur",
    "provocative",
    "naked",
    "boobs",
    "breasts",
    "butt",
    "ass",
    "thong",
    "panties",
    "masturbate",
    "orgasm",
    "climax",
    "hotwife",
    "bdsm",
    "submission",
    "dominatrix",
    "spanking",
    "roleplay",
    "arousal",
    "seduction",
    "moan",
    "foreplay",
    "cuckold",
    "penetration",
    "taboo",
    "swinger",
    "kink",
    "adult chat",
    "webcam",
    "squirting",
    "intimate",
    "g-spot",
    "sex toy",
    "erotica",
    "smut",
    "lewd",
    "provocative clothing",
    "wet",
    "explicit video",
    "sexualized",
    "lust",
    "desire",
    "seductive",
    "exotic dancer",
    "underwear",
    "explicit text",
    "dirty talk",
    "sexual act",
    "arouse",
    // Add more explicit words here
  ],
  drugs: [
    "cocaine",
    "heroin",
    "meth",
    "weed",
    "marijuana",
    "ecstasy",
    "LSD",
    "acid",
    "opioid",
    "oxycodone",
    "fentanyl",
    "ketamine",
    "molly",
    "amphetamine",
    "crack",
    "hash",
    "shrooms",
    "psychedelic",
    "dope",
    "smack",
    "junkie",
    "drug dealer",
    "pills",
    "narcotics",
    "cannabis",
    "THC",
    "CBD",
    "vape",
    "bong",
    "blunt",
    "high",
    "stoned",
    "trip",
    "snorting",
    "injecting",
    "rolling",
    "weed brownie",
    "dabs",
    "wax",
    "opium",
    "popper",
    "methamphetamine",
    "speed",
    "barbiturates",
    "rohypnol",
    "adderall",
    "ritalin",
    "uppers",
    "downers",
    "crystal meth",
    "glue sniffing",
    "substance abuse",
    "hallucinogen",
    "designer drugs",
    "synthetic marijuana",
    "bath salts",
    "magic mushrooms",
    "duster",
    "overdose",
    "drug paraphernalia",
    "black tar",
    "hashish",
    // Add more drug-related words here
  ],
  harmful: [
    "kill",
    "murder",
    "suicide",
    "assassinate",
    "slaughter",
    "hang",
    "stab",
    "shoot",
    "harm",
    "self-harm",
    "violence",
    "genocide",
    "massacre",
    "abuse",
    "bully",
    "terrorism",
    "bomb",
    "threat",
    "rape",
    "hostage",
    "abduction",
    "torture",
    "behead",
    "suffocate",
    "drown",
    "blow up",
    "arson",
    "burn",
    "lynch",
    "molest",
    "strangle",
    "attack",
    "assault",
    "domestic violence",
    "harassment",
    "stalk",
    "knife",
    "gun",
    "weapon",
    "explosion",
    "kidnap",
    "poison",
    "shooting spree",
    "serial killer",
    "mass shooting",
    "school shooting",
    "fighting",
    "war crime",
    "execute",
    "extort",
    "blackmail",
    "death threat",
    "bullying",
    "cyberbullying",
    "abusive language",
    "hangman",
    "incest",
    "infanticide",
    "patricide",
    "matricide",
    "fratricide",
    "revenge killing",
    "lynching",
    "hate crime",
    "terrorist attack",
    "martyrdom",
    "bloodshed",
    "brutality",
    "sadistic",
    "pedophile",
    "pedophilia",
    "child abuse",
    "grooming",
    "child exploitation",
    "child pornography",
    "underage",
    "child predator",
    "rape fantasy",
    "trafficking",
    "human trafficking",
    "sex trafficking",
    "exploitation",
    "non-consensual",
    "revenge porn",
    "abusive partner",
    "stalker",
    "predator",
    "pervert",
    "child abduction",
    "child molestation",
    "online predator",
    "cyberstalker",
    "child grooming",
    "lure",
    "abduction",
    // Add more harmful words here
  ],
}

export const checkForBannedWords = (text: string): string | null => {
  const lowercaseText = text.toLowerCase()

  for (const [category, words] of Object.entries(bannedWords)) {
    for (const word of words) {
      if (lowercaseText.includes(word.toLowerCase())) {
        return `Contains banned ${category} content. Please revise your input.`
      }
    }
  }

  return null
}
